# Project-wide Gradle settings
org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m -Dfile.encoding=UTF-8
org.gradle.parallel=false

android.suppressUnsupportedCompileSdk=34,35
android.useAndroidX=true
android.nonTransitiveRClass=false
android.enableJetifier=true
kotlin.code.style=official

# Compose
android.experimental.enableComposeCompilerMetrics=true
android.experimental.enableComposeCompilerReports=true

# Kotlin
kotlin.incremental=false
kotlin.incremental.usePreciseJavaTracking=true
kotlin.daemon.useFallback=true
kotlin.daemon.jvmargs=-Xmx2048m

# Kapt
kapt.incremental.apt=false
kapt.use.worker.api=false
kapt.include.compile.classpath=false
kapt.verbose=false
kapt.correctErrorTypes=true
kapt.show.processor.stats=true
